version: "2"

services:
    nginx:
        image: nginx:latest
        container_name: "${PROJECT_NAME}_nginx"
        ports:
            - "80:80"
        volumes:
            - ./src:/home/docker/public
            - ./media/uploads:/home/docker/media/uploads
            - ./src/assets:/home/docker/media/assets
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - django

    django:
        build: .
        hostname: "${PROJECT_NAME}_django"
        container_name: "${PROJECT_NAME}_django"
        command: bash -c "sudo gunicorn --reload ${PROJECT_NAME}.wsgi -b 0.0.0.0:80"
        expose:
            - 80
        volumes:
            - ./src:/home/docker/public
            - ./media/uploads:/home/docker/media/uploads
            - ./src/assets:/home/docker/media/assets
            - ./docker-templates/zsh:/home/docker/zsh
        links:
            - postgresql:postgresql
        depends_on:
            - postgresql
        environment:
            - C_FORCE_ROOT=false

    postgresql:
        image: postgres:9.3
        hostname: "${PROJECT_NAME}_db"
        container_name: "${PROJECT_NAME}_db"
        volumes_from:
            - data
        environment:
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_DB: "${DB_NAME}"

    data:
        image: postgres:9.3
        hostname: "${PROJECT_NAME}_postgres_data"
        container_name: "${PROJECT_NAME}_postgres_data"
        volumes:
            - /var/lib/postgresql/data
        command: "true"
